start_watering:
  description: Start watering a zone
  fields:
    entity_id:
      description: Device
      example: "switch.backyard_zone"
    duration:
      description: Number of minutes to water the zone
      example: 15

stop_watering:
  description: Stop watering a zone
  fields:
    entity_id:
      description: Device
      example: "switch.backyard_zone"


# https://developers.home-assistant.io/docs/dev_101_services/
# https://community.home-assistant.io/t/adding-a-service-with-handler/39627